- hosts: localhost
  tasks:
      - import_role: { name: jo }
      - import_role: { name: starship }
      - import_role: { name: colorpedia }
      - import_role: { name: ripgrep }
      - import_role: { name: kitty }
